Feature/tnw new responsive
ccobasi/The-Next-Web-2 pull request #1
Opened 2021-01-22 15:25 UTC by ccobasi

# Clone of The Next Web

 Version Control, Github Flow
 Introduction to HTML5 & CSS3.
 Position, Flex, Grid, Floats, RWD
 Font, Image, Page Size manipulation with new CSS3 features.

2021-01-22 20:57 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] in short, the project is missing a lot of things, i'm going to list a brief list of what's missing, please make the website looks exactly like the original one, and test the project before asking for a review
- [ ] fix linter issues
- [x] fix your live version in your README.md
- [ ] make more commits, and make sure they are descriptive.
- [ ] The black navbar is _not_ black, please fix it
- [ ] the desktop version is completely broken and looked like a mobile version, please fix all sections (footer is fine, but make it's width 100% of the viewport width so it doesn't stay shrank as right now)
- [ ] add all categories in the category section
- [ ] the categories section doesn't 
- [ ] the last funding section should be 4 cards on desktop and reduced to 3 on tablet and mobile
- [ ] make the layout and spacings more similar to the website
- [ ] your mobile version is completely broken as well
- [ ] make sure your sections are centered like in the website. (example the categories section)
- [ ] make sure you use DRY code (DRY = Don't Repeat Yourself), for example, you used `display: flex` 10 times, you can instead make a class named `flex` and use it on any element you're turning into it.
- [ ] again, please make sure you **clone** the website, follow the layout, spacing and design, _then_ ask for a re-review.

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-23 01:03 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @ccobasi 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [ ] Live link is not working in the README file.
- [ ] Screenshot image is missing in the README file.
- [ ] This branch has conflicts please resolve them.
- [ ] Remove inline styling from all the HTML document.
- [ ] **The desktop version is completely broken and looked like a mobile version, please fix all sections (footer is fine), Please follow the previous TSE's suggestion**
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-01-23 01:03 UTC, umairarshadbutt commented on style.css
> +  margin: 0 !important;
Please remove `!important`

2021-01-23 01:03 UTC, umairarshadbutt commented on index.html
> +              <img src="img/12.jpg" alt="hard-fork" style="width: 100%" />
Remove inline styling from all the HTML document

2021-01-23 17:05 UTC, Georjane requested changes
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Very nice work you have done with the TNW website clone. You are almost there. You have just the following few changes to make to get this project approved:

- [ ] Please make sure your Readme file has only one live link to the project
- [x] For the navigation bar, in the large screen size, you have just one navigation row instead of two. It contains the main navigation row and a sub-navigation row.
- [x] For the top 3 articles section, for large screen sizes too, It contains TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/)) which disappears for medium size screen.

This will be all for now. Please submit for another code review when you are done.

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

2021-01-23 18:07 UTC, Georjane approved these changes
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Great job on implementing the required changes. It's a thumbs up for me. 👍 
You can go ahead and merge this PR. 

Goodluck on your next project and Happy Coding 💻

2021-01-23 18:14 UTC, merged